"""empty message

Revision ID: e925187a2632
Revises: 45ad61f1f207
Create Date: 2026-04-01 18:33:06.254927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e925187a2632'
down_revision = '45ad61f1f207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.drop_column('pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
